[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
solc_version = "0.8.26"
remappings = ["@openzeppelin/=node_modules/@openzeppelin/","@openzeppelin/=node_modules/@openzeppelin/"]   # a list of remappings
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
